name: 'Test Coverage Backend'

on: 
  push:
    branches: [ci/cd]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.MY_PAT }}

      - name: Set up Node.js 17.x
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci
        working-directory: ./client/web/example
        run: |
          npm ci
          npm install konva canvas

      - name: Build
        working-directory: ./client/web/example
        run: npm run build --if-present

      - name: Test
        working-directory: ./client/web/example
        run: npm test -- --coverage --watchAll=false

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
