name: 'Test Coverage Backend'

on: pull_request

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.MY_PAT }}
          fetch-depth: 2

      - name: Start containers
        working-directory: ./
        run: docker-compose -f docker-compose.integration-test.yml up --build -d

      - name: Sleep for 60 seconds and wait for containers to start
        uses: jakejarvis/wait-action@master
        with:
         time: '60s'

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Get Coverage
        working-directory: ./go/api
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
