name: 'Test Coverage'

on: pull_request

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 12, 14, 16 ]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.MY_PAT }}

      - name: Start containers
        working-directory: ./
        run: docker-compose -f docker-compose.integration-test.yml up --build -d

      - name: Sleep for 60 seconds and wait for containers to start
        uses: jakejarvis/wait-action@master
        with:
         time: '60s'

      # - name: Wait for containers startup
      #   run: sleep 1m
      #   shell: bash

      - name: Set up Node.js 17.x
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci
        working-directory: ./client/web/example
        run: |
          npm ci
          npm install konva canvas

      - name: Build
        working-directory: ./client/web/example
        run: npm run build --if-present

      - name: Test
        working-directory: ./client/web/example
        run: npm test -- --coverage --watchAll=false

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
