name: 'Test Coverage Backend'

on: 
  push:
    branches: [ci/cd]

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.MY_PAT }}

     - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        working-directory: ./go/api
        run: go build -v ./...

      - name: Test
        working-directory: ./go/api
        run: go test -cover -v ./...

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
