name: 'Go API Test'

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        working-directory: ./go/api
        run: go build -v ./...

      - name: Start containers
        working-directory: ./
        run: docker-compose -f docker-compose.integration-test.yml up --build -d

      - name: Sleep for 60 seconds and wait for containers to start
        uses: jakejarvis/wait-action@master
        with:
         time: '60s'

      # - name: Wait for containers startup
      #   run: sleep 1m
      #   shell: bash

      - name: Test
        working-directory: ./go/api
        run: go test -cover -v ./...
