name: Go Scheduler

on:
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      working-directory: ./go/scheduler
      run: go build -v ./...

    - name: Test
      working-directory: ./go/scheduler
      run: go test -v ./...
